version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/whatsapp_bot
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./middleware:/app
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsapp_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: